tasks/sync-fork.js
A change which was missing inside the #33. 
- Adjusts the check for tracked changes after the `git merge` command.
=> fix(sync-fork): adjust commit message handling

tasks/sync-fork.js
This pull request introduces several improvements regarding the synchronization workflow task.
- Add minor documentation
- Conclude additional unrelated changes inside merge task
The last changes include an enhancement that we don't want to handle with changes regarding `namespaces` and  `defaultElementTemplates` from the Camunda Modeler. We could consider adjusting the cleaning process by simply remove all "Deleted by us" conflicts. But then we could run into lost changes.
=> Synchronization task improvements

client/src/app/tabs/bpmn/custom/CustomPaletteProvider.js, client/src/app/tabs/bpmn/custom/__tests__/CustomPaletteProviderSpec.js, client/src/app/tabs/bpmn/custom/__tests__/CustomReplaceMenuProviderSpec.js, client/src/app/tabs/bpmn/custom/modeler-options/Options.js
This pull request fixes the following issue:
Remove SendTask from pallete and morph menu
Closes #63
=> Remove SendTask from pallete and morph menu

client/src/app/tabs/bpmn/custom/__tests__/CustomReplaceMenuProviderSpec.js, client/src/app/tabs/bpmn/custom/modeler-options/Options.js
This pull request fixes the following issue:
* I can morph an intermediate message catch event into a timer event
Closes #70
=> Morph an intermediate message catch event into a timer event

client/src/app/tabs/bpmn/custom/properties-provider/parts/SequenceFlowProps.js
Since [we did major work in the original properties panel](https://github.com/bpmn-io/bpmn-js-properties-panel/commit/0b8637560e16b683aac6ae90c11257c58ae28df3) we don't need much to do in this case. Only detected one additional place for a possible injection.
Closes #83
=> chore(custom/properties-provider): properly escape html

client/src/app/tabs/bpmn/custom/CustomReplaceMenuProvider.js, client/src/app/tabs/bpmn/custom/CustomRules.js, client/src/app/tabs/bpmn/custom/__tests__/CustomContextPadProviderSpec.js, client/src/app/tabs/bpmn/custom/__tests__/CustomReplaceMenuProviderSpec.js, client/src/app/tabs/bpmn/custom/modeler-options/Options.js, client/src/app/tabs/bpmn/custom/properties-provider/ZeebePropertiesProvider.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/BoundaryEventTimerEventDefinitionSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/MultiInstanceLoop.bpmn, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/MultiInstanceLoopSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/StartEventTimerEventDefinitionSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/MultiInstanceProps.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/TimerEventProps.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/InputOutput.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/MultiInstanceLoopCharacteristics.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/PayloadMappings.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/TimerEventDefinition.js, client/src/app/tabs/bpmn/custom/zeebe-bpmn-moddle/zeebe.json
Closes #82
This adds support to annotate `bpmn:ServiceTask`, `bpmn:ReceiveTask` and `bpmn:SubProcess` elements with the multi-instance marker. It also adds the related Zeebe properties to the provider. As discussed with the @saig0, the `inputCollection` property is configured as _required_.
=> Multi Instance Support

client/src/app/tabs/bpmn/custom/modeler-options/Options.js, client/src/app/tabs/bpmn/custom/properties-provider/ZeebePropertiesProvider.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/Error.bpmn, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/ErrorSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/ErrorProps.js
Fixes #85 
This pr adds Error Boundary Event into replace menu. 40 tests implemented to cover get/set/remove/switch-between-error-events cases.
=> feat(client): error boundary event support

client/src/app/tabs/bpmn/custom/__tests__/CustomPaletteProviderSpec.js, client/src/app/tabs/bpmn/custom/modeling/__tests__/CreateZeebeBoundaryEventBehaviorSpec.js, client/src/app/tabs/bpmn/custom/modeling/behavior/CreateZeebeBoundaryEventBehavior.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutput.bpmn, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutputSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/helper/InputOutputHelper.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/TimerEventProps.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/InputOutput.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/TimerDurationDefinition.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/TimerEventDefinition.js
To make the Zeebe custom implementations a little more stable for the next release (#97), I took a run through the codebase and ship a couple of improvements.
* Create a complete test suite for `zeebe:IoMapping` properties
* Refactor the `ZeebeCreateBoundaryEventBehavior`
* Add test coverage for the `CustomPaletteProvider`
* Refactor the overall `TimerEventProps` implementation
---
Related to #87
=> Refactor Zeebe customs

tasks/sync-fork.js
Ensures we do not accidentally create and push non-related release tags (from the Camunda Modeler) when executing the syncing workflow.
Closes #101
=> fix(sync-fork): remove unnecessary tags after merge

client/src/app/tabs/bpmn/custom/properties-provider/ZeebePropertiesProvider.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/TaskDefinitionSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/TaskDefinitionProps.js
I found out that the input validation for the task definition type property isn't working currently as expected. This fixes it.
=> fix(client/properties-provider): fix validation for task definition type

client/src/app/tabs/bpmn/custom/CustomContextPadProvider.js, client/src/app/tabs/bpmn/custom/__tests__/CustomContextPadProviderSpec.js
Necessary due to [breaking changes in `diagram-js@5.0.0`](https://github.com/bpmn-io/diagram-js/blob/develop/CHANGELOG.md#500),
Closes #110
=> fix(client/context-pad-provider): set source on drag start

resources/plugins/test/assets/logo-template.svg, resources/plugins/test/assets/logo.svg, resources/plugins/test/menu.js
This sets the color of the development logo inside the Editor, for a better distinction to the Camunda Modeler, at least in dev mode. Discussed in [our last Weekly](distinguishable).
It also removes the node hacks from the test plugin, as we already did in the Camunda Modeler, cf. https://github.com/camunda/camunda-modeler/commit/02e909df5ae467bd3f47874ffba1e5057a1d34b9
=> Development Logo

client/src/app/tabs/bpmn/custom/CustomReplaceMenuProvider.js, client/src/app/tabs/bpmn/custom/__tests__/CustomReplaceMenuProviderSpec.js, client/src/app/tabs/bpmn/custom/__tests__/diagram.bpmn, client/src/app/tabs/bpmn/custom/modeler-options/Options.js
This aligns the `ReplaceMenu` with the one of the Camunda Modeler. Furthermore, it adds missing replace options to ensure forward-and-backward type switching, e.g. in modeling events or tasks.
Additionally, it re-structures the overall test suite for the `ReplaceMenuProvider` and adds test coverage for several replace scenarios (e.g. boundary events, event-sub-processes, participants).
Closes #115
=> Align Replace Menu

client/src/app/tabs/bpmn/custom/properties-provider/__tests__/MultiInstanceLoopSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/MultiInstanceLoopCharacteristics.js
Cf. Multi-Instance properties. Currently, these props will not be deleted when clicking the "X" removing button inside the properties panel. That leads to stuff like this.
```xml
<bpmn:serviceTask id="ServiceTask_06yk2gv">
<bpmn:multiInstanceLoopCharacteristics>
<bpmn:extensionElements>
<zeebe:loopCharacteristics inputCollection="" inputElement="" outputCollection="" outputElement="" />
</bpmn:extensionElements>
</bpmn:multiInstanceLoopCharacteristics>
</bpmn:serviceTask>
```
Therefore this pull requests ensures the properties also got removed from the business object if deleted in the panel.
=> fix(client): remove props from business object if deleted in panel

client/src/app/tabs/bpmn/custom/CustomReplaceMenuProvider.js, client/src/app/tabs/bpmn/custom/__tests__/CustomReplaceMenuProviderSpec.js, client/src/app/tabs/bpmn/custom/__tests__/diagram.bpmn, client/src/app/tabs/bpmn/custom/modeler-options/Options.js, client/src/app/tabs/bpmn/custom/properties-provider/ZeebePropertiesProvider.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/CallActivity.bpmn, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/CallActivitySpec.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutput.bpmn, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutputSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/helper/InputOutputHelper.js, client/src/app/tabs/bpmn/custom/properties-provider/helper/__tests__/InputOutputHelperSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/helper/__tests__/diagram.bpmn, client/src/app/tabs/bpmn/custom/properties-provider/parts/CallActivityProps.js, client/src/app/tabs/bpmn/custom/zeebe-bpmn-moddle/zeebe.json
Closes #118 
____
Note: We now implement the first round for the properties, which includes _two_ input fields for the `processId` and `processIdExpression`. We will improve this by having _only one_ input field in a follow-up task: cf. https://github.com/zeebe-io/zeebe-modeler/issues/130
=> Call Activity Support

tasks/sync-fork.js
Related to #126
In order we want to pull in the latest Camunda Modeler changes, this PR add the `plugins` folder from the excluded directories while the synchronization. This will prevent the `deployment-tool` to be added to the Zeebe Modeler.
Tested it with an example synchronization
```js
$ npm run sync -- -t 3.4.1
```
=> chore(sync-fork): add plugins folder to excluded directories

client/src/app/tabs/bpmn/custom/properties-provider/__tests__/BoundaryEventTimerEventDefinition.bpmn, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/EventSubProcessTimerEventDefinitionSpec.bpmn, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/EventSubProcessTimerEventDefinitionSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/TimerEventProps.js
Related to #156
I added some test cases to verify the new selection options for timer event definitions introduced by https://github.com/zeebe-io/zeebe-modeler/pull/157. 
(Simply forgot to check whether we added some tests for that while making the review...)
=> test(properties-provider): add test coverage for timer event definitions

README.md
Better place is our internal `docs/.project` documentation
----
Related to https://github.com/zeebe-io/zeebe-modeler/pull/175
=> docs(README): remove upstream sync

build/entitlements.mac.inherit.plist
Closes #179
What causes #179 and why this fix works:
As mentioned [here by Apple](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation), library validation prevents an app from loading frameworks, plug-ins, or libraries unless they’re either signed by Apple or signed with the same team ID as the app. Thats why the gRPC module caused problems in macOS environment. This fix simply disables the library validation feature using the related configuration.
=> Disable library validation for notarization

client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js, client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginModal.js, client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginModalSpec.js, client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js, client/src/plugins/zeebe-plugin/shared/ZeebeConnectionValidator.js, client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js, client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
Create separate config places for per-file deployment configuration and zeebe endpoints.
Closes #190
=> feat(zeebe-plugin): persist endpoints and deployment config separately

client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js, client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js, client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js, client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
This ensures we're saving tab changes before the Deployment Modal got opened.
Furthermore, it ensures we do not run into an error when we canceled the saving dialog on start instance feature (and deployment)
Closes #199
=> Save Tab before Deploy

.travis.yml, tasks/distro.js
This sets up Windows CI on Travis for both distro and nightly builds. To select proper certificate, we use the cert's fingerprint as the cert subject apparently did not work (cf. https://travis-ci.com/github/zeebe-io/zeebe-modeler/jobs/319668343#L338).
Closes #192
Proof it builds: https://travis-ci.com/github/zeebe-io/zeebe-modeler/jobs/319688610
=> Setup Windows CI for nightly & distro builds

.travis.yml, tasks/distro.js
This sets up Windows CI on Travis for both distro and nightly builds. To select proper certificate, we use the cert's fingerprint as the cert subject apparently did not work (cf. https://travis-ci.com/github/zeebe-io/zeebe-modeler/jobs/319668343#L338).
Closes #192
Proof it builds: https://travis-ci.com/github/zeebe-io/zeebe-modeler/jobs/319688610
Implements https://github.com/zeebe-io/zeebe-modeler/pull/207 reverted by mistake.
=> Setup Windows CI for nightly & distro builds #2

docs/.project/RELEASE_CHECKLIST.md
Closes https://github.com/zeebe-io/zeebe-modeler/issues/219
Requires https://github.com/bpmn-io/internal-docs/pull/110
=> chore(docs): update release email template link

package-lock.json, package.json, tasks/sync-fork.js
This is not implemented as I couldn't set it up correctly together with `git merge` (fetch with `--no-tags` made it impossible to refer to the tag later).
This apparently works correctly after update of `simple-git`.
Closes #247
=> Improve sync script

client/src/app/tabs/bpmn/custom/properties-provider/parts/SequenceFlowProps.js
__Solution__
The <button> element was missing a class defining the layout of the `x` clear button
Closes https://github.com/zeebe-io/zeebe-modeler/issues/268
=> Fix condition expression input layout

client/package-lock.json, client/package.json, client/src/app/tabs/bpmn/modeler/BpmnModeler.js
__Description__
Bumps zeebe-bpmn-moddle to v0.3.0 and integrates the new moddle extension.
The extension ensures that properties are allowed to be copied when replacing elements.
Eg. a `CallActivity` with a `calledElement` attribute changed to a simple `Task` won't have its `calledElement` copied because it's not allowed on `Task` elements, in accordance with the json schema.
The schema itself is incomplete in its current version and doesn't specify for instance that a `<zeebe:TaskDefinition>` isn't allowed on anything else than a `ServiceTask`, implicitely allowing the property to be copied regardless of the parent element's type.
See https://github.com/zeebe-io/zeebe-bpmn-moddle/issues/4 for context
Closes #248 
__Definition …
=> Integrate zeebe-bpmn-moddle extension

CHANGELOG.md, client/package-lock.json, client/package.json, client/src/app/tabs/bpmn/custom/modeling/__tests__/CreateZeebeCallActivityBehaviorSpec.js, client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorIntegrationSpec.js, client/src/app/tabs/bpmn/custom/modeling/__tests__/UpdatePropagateAllChildVariablesBehaviorSpec.js, client/src/app/tabs/bpmn/custom/modeling/__tests__/process-call-activities.bpmn, client/src/app/tabs/bpmn/custom/modeling/behavior/CreateZeebeCallActivityBehavior.js, client/src/app/tabs/bpmn/custom/modeling/behavior/UpdatePropagateAllChildVariablesBehavior.js, client/src/app/tabs/bpmn/custom/modeling/behavior/index.js, client/src/app/tabs/bpmn/custom/modeling/helper/CalledElementHelper.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutput.bpmn, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutputSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/OutputParameterToggleSpec.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/CallActivityProps.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/InputOutput.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/InputOutputParameter.js, client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/OutputParameterToggle.js
Closes #252
Closes #267
This includes three key changes to support the new
propagateAllChildVariables attribute on calledElement extensionElements:
(1): Behavior to initialize callActivities with
propagateAllChildVariables set to false per default (CreateZeebeCallActivityBehavior)
(2): toogle UI component to controll the attribute and to display it
accordingly to engine logic in case it is not set (legacy diagrams)
(OutputParameterToggle)
(3): behavior to keep the attribute in sync with outputParameters
(UpdatePropagateAllChildVariablesBehavior)
=> feat: support propagateAllChildVariables attribute on callActivities

client/src/app/tabs/bpmn/custom/properties-provider/ZeebePropertiesProvider.js, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/ParticipantProcess.bpmn, client/src/app/tabs/bpmn/custom/properties-provider/__tests__/ParticipantProcessSpec.js
Closes #278
Adds the inputs to edit a participant's process name and id to the properties panel.
=> Add process id of participant to properties panel
