zeebe-io/zeebe-modeler

README.md

Adds the CI badge which will be green in a bit :partly_sunny:.

docs(README): add CI badge

---

package-lock.json

After the last synchronization (#50) the build got broken because of a missing `package-lock.json` update. Therefore, here are the missing updates.

chore(project): update package-lock.json

---

README.md
docs/.project/RELEASE_CHECKLIST.md

Switch to develop

---

client/src/app/tabs/bpmn/custom/CustomContextPadProvider.js
client/src/app/tabs/bpmn/custom/__tests__/CustomContextPadProviderSpec.js
client/src/app/tabs/bpmn/custom/__tests__/diagram.bpmn

fix(client/context-pad-provider): restrict context pad for labels

---

docs/.project/INTEGRATION_TEST.md

Updated integration test steps based on Zeebe modeller capabilities.

feat(integration-test): update test cases based on Zeebe modeller

---

CHANGELOG.md

chore(CHANGELOG): update to v0.7.0

---

client/src/app/tabs/bpmn/custom/properties-provider/ZeebePropertiesProvider.js
client/src/app/tabs/bpmn/custom/properties-provider/__tests__/ZeebePropertiesProvider.bpmn
client/src/app/tabs/bpmn/custom/properties-provider/__tests__/ZeebePropertiesProviderSpec.js

This aligns the Properties Panel with the one of the Camunda Modeler.
Closes #116

feat(client/properties-provider): add details group

---

client/src/app/tabs/bpmn/custom/CustomContextPadProvider.js
client/src/app/tabs/bpmn/custom/__tests__/CustomContextPadProvider.bpmn
client/src/app/tabs/bpmn/custom/__tests__/CustomContextPadProviderSpec.js
client/src/app/tabs/bpmn/custom/modeler-options/Options.js

Align Context Pad

---

client/src/app/tabs/bpmn/custom/CustomReplaceMenuProvider.js
client/src/app/tabs/bpmn/custom/__tests__/CustomReplaceMenuProviderSpec.js

feat(client/properties-provider): multi instance option to none tasks

---

client/src/app/TabsProvider.js

fix(client): update modeling tutorial link

---

client/src/app/tabs/bpmn/custom/properties-provider/__tests__/Message.bpmn
client/src/app/tabs/bpmn/custom/properties-provider/__tests__/MessageSpec.js
client/src/app/tabs/bpmn/custom/properties-provider/parts/MessageProps.js

feat(client): add correlationKey to message event sub process

---

client/src/app/tabs/bpmn/custom/properties-provider/parts/TimerEventProps.js

Align timer event subprocess start event definitions with boundary event

---

client/src/app/tabs/bpmn/custom/__tests__/CustomReplaceMenuProviderSpec.js
client/src/app/tabs/bpmn/custom/modeler-options/Options.js
client/src/app/tabs/bpmn/custom/properties-provider/__tests__/Error.bpmn
client/src/app/tabs/bpmn/custom/properties-provider/__tests__/ErrorSpec.js

Add error end event

---

app/lib/menu/menu-builder.js

Closes #168
It seems like the changes we introduced in #141 got lost in the last release, maybe with the sync we did before and while fixing merge conflicts, cf. #145 
We should ensure in the future, that this does not happen again

fix(app): correct documentation

---

README.md

I've added the installation instructions for Scoop users.
None.

chore(README): add instructions for installation with Scoop

---

docs/.project/UPSTREAM_SYNC.md

Adding upstream sync document outside main README.

docs(project): add UPSTREAM_SYNC document

---

client/src/app/EmptyTab.js

Add new button styles to EmptyTab

---

client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js

chore(zeebe-plugin): fix typo <Camunda> -> <Zeebe>

---

client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginModalSpec.js

Adds a test case to verify bugs like #190 would be detected in the future.

test(zeebe-plugin): add test case for initial deployment name

---

client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js

Reset isStart flag on icon click

---

client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginModal.js
client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginModalSpec.js
client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginValidatorSpec.js
client/src/plugins/zeebe-plugin/deployment-plugin/ui/Radio.js
client/src/plugins/zeebe-plugin/shared/ZeebeAuthTypes.js
client/src/plugins/zeebe-plugin/shared/ZeebeConnectionValidator.js
client/src/plugins/zeebe-plugin/shared/ZeebeTargetTypes.js

Differentiate between auth and deployment target

---

.github/PULL_REQUEST_TEMPLATE.md

feat(project): add acceptance criteria to PR template

---

client/src/app/tabs/bpmn/custom/properties-provider/__tests__/InputOutputSpec.js
client/src/app/tabs/bpmn/custom/properties-provider/__tests__/TaskDefinitionSpec.js
client/src/app/tabs/bpmn/custom/properties-provider/parts/TaskDefinitionProps.js
client/src/app/tabs/bpmn/custom/properties-provider/parts/implementation/InputOutputParameter.js

Allow expressions with spaces

---

CHANGELOG.md
client/src/app/tabs/bpmn/custom/properties-provider/helper/InputOutputHelper.js
client/src/app/tabs/bpmn/custom/properties-provider/helper/__tests__/InputOutputHelperSpec.js

allow outputMappings for all events

---

CHANGELOG.md

chore(CHANGELOG): update to v0.10.0-rc.0

---

client/src/app/tabs/bpmn/custom/properties-provider/__tests__/CallActivitySpec.js
client/src/app/tabs/bpmn/custom/properties-provider/parts/CallActivityProps.js

Closes https://github.com/zeebe-io/zeebe-modeler/issues/237

fix: refuse non QName process ids
